DROP TABLE IF EXISTS MEMBER;

CREATE TABLE MEMBER (
    id INT AUTO_INCREMENT PRIMARY KEY ,
    firstName VARCHAR(80) NOT NULL ,
    lastName VARCHAR(80) NOT NULL ,
    email VARCHAR(120),
    phone VARCHAR(20) NOT NULL ,
    dateOfBirth VARCHAR(120) NOT NULL
);

